FROM quay.io/centos/centos:stream9

COPY ./virt-exportserver-v0.59.0-linux-ppc64le /usr/bin/virt-exportserver

RUN groupadd -g 1001 nonroot-user && useradd -u 1001 -g 1001 -Ms /bin/sh nonroot-user

USER 1001

CMD ["virt-exportserver"]
