FROM quay.io/centos/centos:stream8

RUN yum install -y --allowerasing acl curl vim-minimal \
    coreutils-single glibc-minimal-langpack libcurl-minimal \
    libvirt-client.ppc64le \
    libvirt-daemon-driver-qemu.ppc64le \
    qemu-kvm-core.ppc64le \
    ethtool findutils iptables nftables nmap-ncat procps-ng selinux-policy selinux-policy-targeted tar xorriso \
    daxctl-libs systemd

RUN setcap 'cap_net_bind_service=+ep' /usr/libexec/qemu-kvm

RUN unlink /usr/bin/nc && ln -s /usr/bin/ncat /usr/bin/nc

COPY ./virt-launcher-v0.58.0-linux-ppc64le /usr/bin/virt-launcher
COPY ./nsswitch.conf /etc/nsswitch.conf
COPY ./virtqemud.conf /etc/libvirt/virtqemud.conf
COPY ./qemu.conf /etc/libvirt/qemu.conf
COPY ./container-disk-v0.58.0-linux-ppc64le /usr/bin/container-disk
COPY ./node-labeller/node-labeller.sh /usr/bin/node-labeller.sh
COPY ./virt-freezer-v0.58.0-linux-ppc64le /usr/bin/virt-freezer
COPY ./virt-launcher-monitor-v0.58.0-linux-ppc64le /usr/bin/virt-launcher-monitor
COPY ./virt-probe-v0.58.0-linux-ppc64le /usr/bin/virt-probe
